### ISSUE TITLE
Javascript timer is slower than in reality

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#117]
Countdown timer in Overview/Fleet tabs decrease slower by a little factor. Refreshing website after eg. 1 minute shows different time.
Probably javascript library inaccuracy.

**Comment by booster916** [comment]
I saw the same problem when playing steemnova. I have to refresh the site every time to time my attacks and counterattacks perfectly

**Comment by mys** [comment]
Probable solution: instead of subtraction time (-1s) every 1 second, make comparison of downloaded time and current datetime.

**Comment by IntinteDAO** [comment]
Why is there a problem?
The program takes an hour and every 1000ms increases the time by 1 second, which is generally true.

The problem is that the code (setInterval) is not accurate. I mean, it works at a minimum of 1000ms, not every 1000ms

If I understand the principle of operation (I do not program in Javascript), it is:
- START point
- The code is executed (100ms for example)
- Wait 1 second and execute the upgrade code)
- The code is executed (100ms for example)
- Wait 1 second and execute the upgrade code)
- The code is executed (100ms for example)
- Wait 1 second and execute the upgrade code)

We're just 300ms late. If the browser slows down, etc., this time can increase even more.

Currently we have a fix that works well (but not very well). Slowdowns do not cause long delays (even very small ones), but a quick second jump can happen.

Another option is to take time from the server every second, but for now I think it's unnecessary. Anyway, the bug is probably fixed. On the test version of SteemNova it is not visible (or so visible).
