### ISSUE TITLE
Spy probes got destroyed vs empty planet, bug?

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#13]
![image](https://user-images.githubusercontent.com/17079510/35781994-b9e65840-09f1-11e8-9ca8-cc3ae253a5e5.png)

**Comment by Qwatayean** [comment]
The chance of being destroyed, or not, is based on techs instead of fleet and the amount of spy probes sent. It runs through random number.
`$targetChance 	= mt_rand(0, min(($fleetAmount/4) * ($targetSpyTech / $senderSpyTech), 100));`
`$spyChance  	= mt_rand(0, 100);`

Where the spy probes are killed.
`if ($targetChance >= $spyChance)`

You can check this in includes/classes/missions/MissionCaseSpy.class.php
