### ISSUE TITLE
Adjust player's banner to other languages

### ISSUE THREAD

**Issue by mys** [steemnova/steemnova#31]
It generates messages in Polish language (admin panel lang?)
![image](https://user-images.githubusercontent.com/17079510/36353114-85db566e-14c2-11e8-972b-1a3c7dd94ffa.png)

**Comment by MWFIAE** [comment]
For me its correct (german)
![image](https://user-images.githubusercontent.com/6072971/36353982-ef750c22-14cd-11e8-8920-d6006d89c52c.png)

**Comment by mys** [comment]
@MWFIAE good to know, I have to check other languages tho

**Comment by Qwatayean** [comment]
Hi, the language of the banner is based on the browser and not in the user language itself.

You can check that on Language.class.php, `	public function getUserAgentLanguage()`

Because there is `$LNG->getUserAgentLanguage();` on root/userpic.php, it will always return browser language instead of user itself.
